services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ci-example
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    environment:
      DB_URL: postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@db:5432/ci-example
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/ 
    ports:
      - "8080:8080"
    depends_on:
     - backend

volumes:
  db_data:
    driver: local
