"""Topic search index

Revision ID: 581e8ae121ad
Revises: 79c024641334
Create Date: 2025-04-11 01:26:05.601508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581e8ae121ad'
down_revision: Union[str, None] = '79c024641334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    # ### end Alembic commands ###
